---
- hosts: localhost
  tasks:
   - name: create a VPC with dedicated tenancy and a couple of tags
     ec2_vpc_net:
      name: Module_dev2
      cidr_block: 10.10.0.0/16
      region: us-east-2
     register: vpcout
   - debug:
      var: vpcout

   - name: creating subentes in vpc
     ec2_vpc_subnet:
      vpc_id: "{{vpcout.vpc.id}}"
      state: present
      cidr: 10.10.0.0/20
      region: us-east-2
      az: us-east-2a
     register: subnet_out



   - name: creating internet gateway
     ec2_vpc_igw:
      vpc_id: "{{vpcout.vpc.id}}"
      state: absent
      region: us-east-2
     register: igw

   - name: creating route table
     ec2_vpc_route_table:
      vpc_id: "{{vpcout.vpc.id}}"
      region: us-east-2
      state: present
     register: route_out

   - debug:
      var: "{{item}}"
     loop:
      - subnet_out
      - igw
      - route_out
# updated
...